# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        speech emotion recognition: 3
        sentiment analysis: 3
        utterance classification: 2
        cnn-lstm: 3

# 通知の閾値
score_threshold: 0
